// tinycnn_top.sv -- AUTO-GENERATED by generate_tinycnn_sv.py. DO NOT EDIT BY HAND.
// Structural wiring for the 8-conv-layer network defined in tinycnn_pkg.sv.
// Generic engines used: conv_engine.sv, gap_fc_argmax.sv, dp_ram.sv (hand-written, reused as-is).
import tinycnn_pkg::*;

module tinycnn_top (
    input  logic clk,
    input  logic rst_n,

    // preload the input image (already quantized to uint8, CHW flattened) before pulsing start
    input  logic                             img_we,
    input  logic [$clog2(IN_C*IN_H*IN_W)-1:0] img_waddr,
    input  logic [7:0]                       img_wdata,

    input  logic start,
    output logic done,
    output logic [$clog2(NCLS)-1:0] class_id,
    output logic signed [31:0] class_scores [0:NCLS-1]
);

    // ---- activation buffers: buf[0] holds the input image, buf[i+1] holds layer i's output ----
    localparam int BUF0_DEPTH = IN_C*IN_H*IN_W;
    localparam int BUF1_DEPTH = L0_COUT*((L0_HIN+2-3)/L0_STRIDE+1)*((L0_WIN+2-3)/L0_STRIDE+1);
    localparam int BUF2_DEPTH = L1_COUT*((L1_HIN+2-3)/L1_STRIDE+1)*((L1_WIN+2-3)/L1_STRIDE+1);
    localparam int BUF3_DEPTH = L2_COUT*((L2_HIN+2-3)/L2_STRIDE+1)*((L2_WIN+2-3)/L2_STRIDE+1);
    localparam int BUF4_DEPTH = L3_COUT*((L3_HIN+2-3)/L3_STRIDE+1)*((L3_WIN+2-3)/L3_STRIDE+1);
    localparam int BUF5_DEPTH = L4_COUT*((L4_HIN+2-3)/L4_STRIDE+1)*((L4_WIN+2-3)/L4_STRIDE+1);
    localparam int BUF6_DEPTH = L5_COUT*((L5_HIN+2-3)/L5_STRIDE+1)*((L5_WIN+2-3)/L5_STRIDE+1);
    localparam int BUF7_DEPTH = L6_COUT*((L6_HIN+2-3)/L6_STRIDE+1)*((L6_WIN+2-3)/L6_STRIDE+1);
    localparam int BUF8_DEPTH = L7_COUT*((L7_HIN+2-3)/L7_STRIDE+1)*((L7_WIN+2-3)/L7_STRIDE+1);

    logic buf0_we; logic [$clog2(BUF0_DEPTH)-1:0] buf0_waddr; logic [7:0] buf0_wdata;
    logic [$clog2(BUF0_DEPTH)-1:0] buf0_raddr; logic [7:0] buf0_rdata;
    dp_ram #(.DEPTH(BUF0_DEPTH)) u_buf0 (.clk(clk), .we(buf0_we), .waddr(buf0_waddr), .wdata(buf0_wdata), .raddr(buf0_raddr), .rdata(buf0_rdata));
    logic buf1_we; logic [$clog2(BUF1_DEPTH)-1:0] buf1_waddr; logic [7:0] buf1_wdata;
    logic [$clog2(BUF1_DEPTH)-1:0] buf1_raddr; logic [7:0] buf1_rdata;
    dp_ram #(.DEPTH(BUF1_DEPTH)) u_buf1 (.clk(clk), .we(buf1_we), .waddr(buf1_waddr), .wdata(buf1_wdata), .raddr(buf1_raddr), .rdata(buf1_rdata));
    logic buf2_we; logic [$clog2(BUF2_DEPTH)-1:0] buf2_waddr; logic [7:0] buf2_wdata;
    logic [$clog2(BUF2_DEPTH)-1:0] buf2_raddr; logic [7:0] buf2_rdata;
    dp_ram #(.DEPTH(BUF2_DEPTH)) u_buf2 (.clk(clk), .we(buf2_we), .waddr(buf2_waddr), .wdata(buf2_wdata), .raddr(buf2_raddr), .rdata(buf2_rdata));
    logic buf3_we; logic [$clog2(BUF3_DEPTH)-1:0] buf3_waddr; logic [7:0] buf3_wdata;
    logic [$clog2(BUF3_DEPTH)-1:0] buf3_raddr; logic [7:0] buf3_rdata;
    dp_ram #(.DEPTH(BUF3_DEPTH)) u_buf3 (.clk(clk), .we(buf3_we), .waddr(buf3_waddr), .wdata(buf3_wdata), .raddr(buf3_raddr), .rdata(buf3_rdata));
    logic buf4_we; logic [$clog2(BUF4_DEPTH)-1:0] buf4_waddr; logic [7:0] buf4_wdata;
    logic [$clog2(BUF4_DEPTH)-1:0] buf4_raddr; logic [7:0] buf4_rdata;
    dp_ram #(.DEPTH(BUF4_DEPTH)) u_buf4 (.clk(clk), .we(buf4_we), .waddr(buf4_waddr), .wdata(buf4_wdata), .raddr(buf4_raddr), .rdata(buf4_rdata));
    logic buf5_we; logic [$clog2(BUF5_DEPTH)-1:0] buf5_waddr; logic [7:0] buf5_wdata;
    logic [$clog2(BUF5_DEPTH)-1:0] buf5_raddr; logic [7:0] buf5_rdata;
    dp_ram #(.DEPTH(BUF5_DEPTH)) u_buf5 (.clk(clk), .we(buf5_we), .waddr(buf5_waddr), .wdata(buf5_wdata), .raddr(buf5_raddr), .rdata(buf5_rdata));
    logic buf6_we; logic [$clog2(BUF6_DEPTH)-1:0] buf6_waddr; logic [7:0] buf6_wdata;
    logic [$clog2(BUF6_DEPTH)-1:0] buf6_raddr; logic [7:0] buf6_rdata;
    dp_ram #(.DEPTH(BUF6_DEPTH)) u_buf6 (.clk(clk), .we(buf6_we), .waddr(buf6_waddr), .wdata(buf6_wdata), .raddr(buf6_raddr), .rdata(buf6_rdata));
    logic buf7_we; logic [$clog2(BUF7_DEPTH)-1:0] buf7_waddr; logic [7:0] buf7_wdata;
    logic [$clog2(BUF7_DEPTH)-1:0] buf7_raddr; logic [7:0] buf7_rdata;
    dp_ram #(.DEPTH(BUF7_DEPTH)) u_buf7 (.clk(clk), .we(buf7_we), .waddr(buf7_waddr), .wdata(buf7_wdata), .raddr(buf7_raddr), .rdata(buf7_rdata));
    logic buf8_we; logic [$clog2(BUF8_DEPTH)-1:0] buf8_waddr; logic [7:0] buf8_wdata;
    logic [$clog2(BUF8_DEPTH)-1:0] buf8_raddr; logic [7:0] buf8_rdata;
    dp_ram #(.DEPTH(BUF8_DEPTH)) u_buf8 (.clk(clk), .we(buf8_we), .waddr(buf8_waddr), .wdata(buf8_wdata), .raddr(buf8_raddr), .rdata(buf8_rdata));

    // image preload feeds buf0's write port whenever the top-level img_we is asserted
    assign buf0_we    = img_we;
    assign buf0_waddr = img_waddr;
    assign buf0_wdata = img_wdata;

    // ---- per-layer conv_engine instances ----
    logic conv0_start, conv0_done;
    conv_engine #(
        .CIN(L0_CIN), .COUT(L0_COUT), .HIN(L0_HIN), .WIN(L0_WIN), .STRIDE(L0_STRIDE), .CLAMP(1'b1)
    ) u_conv0 (
        .clk(clk), .rst_n(rst_n), .start(conv0_start), .done(conv0_done),
        .in_addr(buf0_raddr), .in_data(buf0_rdata),
        .out_addr(buf1_waddr), .out_data(buf1_wdata), .out_we(buf1_we),
        .weight(L0_WEIGHT), .bias(L0_BIAS), .mult(L0_MULT), .shift(L0_SHIFT)
    );

    logic conv1_start, conv1_done;
    conv_engine #(
        .CIN(L1_CIN), .COUT(L1_COUT), .HIN(L1_HIN), .WIN(L1_WIN), .STRIDE(L1_STRIDE), .CLAMP(1'b1)
    ) u_conv1 (
        .clk(clk), .rst_n(rst_n), .start(conv1_start), .done(conv1_done),
        .in_addr(buf1_raddr), .in_data(buf1_rdata),
        .out_addr(buf2_waddr), .out_data(buf2_wdata), .out_we(buf2_we),
        .weight(L1_WEIGHT), .bias(L1_BIAS), .mult(L1_MULT), .shift(L1_SHIFT)
    );

    logic conv2_start, conv2_done;
    conv_engine #(
        .CIN(L2_CIN), .COUT(L2_COUT), .HIN(L2_HIN), .WIN(L2_WIN), .STRIDE(L2_STRIDE), .CLAMP(1'b1)
    ) u_conv2 (
        .clk(clk), .rst_n(rst_n), .start(conv2_start), .done(conv2_done),
        .in_addr(buf2_raddr), .in_data(buf2_rdata),
        .out_addr(buf3_waddr), .out_data(buf3_wdata), .out_we(buf3_we),
        .weight(L2_WEIGHT), .bias(L2_BIAS), .mult(L2_MULT), .shift(L2_SHIFT)
    );

    logic conv3_start, conv3_done;
    conv_engine #(
        .CIN(L3_CIN), .COUT(L3_COUT), .HIN(L3_HIN), .WIN(L3_WIN), .STRIDE(L3_STRIDE), .CLAMP(1'b1)
    ) u_conv3 (
        .clk(clk), .rst_n(rst_n), .start(conv3_start), .done(conv3_done),
        .in_addr(buf3_raddr), .in_data(buf3_rdata),
        .out_addr(buf4_waddr), .out_data(buf4_wdata), .out_we(buf4_we),
        .weight(L3_WEIGHT), .bias(L3_BIAS), .mult(L3_MULT), .shift(L3_SHIFT)
    );

    logic conv4_start, conv4_done;
    conv_engine #(
        .CIN(L4_CIN), .COUT(L4_COUT), .HIN(L4_HIN), .WIN(L4_WIN), .STRIDE(L4_STRIDE), .CLAMP(1'b1)
    ) u_conv4 (
        .clk(clk), .rst_n(rst_n), .start(conv4_start), .done(conv4_done),
        .in_addr(buf4_raddr), .in_data(buf4_rdata),
        .out_addr(buf5_waddr), .out_data(buf5_wdata), .out_we(buf5_we),
        .weight(L4_WEIGHT), .bias(L4_BIAS), .mult(L4_MULT), .shift(L4_SHIFT)
    );

    logic conv5_start, conv5_done;
    conv_engine #(
        .CIN(L5_CIN), .COUT(L5_COUT), .HIN(L5_HIN), .WIN(L5_WIN), .STRIDE(L5_STRIDE), .CLAMP(1'b1)
    ) u_conv5 (
        .clk(clk), .rst_n(rst_n), .start(conv5_start), .done(conv5_done),
        .in_addr(buf5_raddr), .in_data(buf5_rdata),
        .out_addr(buf6_waddr), .out_data(buf6_wdata), .out_we(buf6_we),
        .weight(L5_WEIGHT), .bias(L5_BIAS), .mult(L5_MULT), .shift(L5_SHIFT)
    );

    logic conv6_start, conv6_done;
    conv_engine #(
        .CIN(L6_CIN), .COUT(L6_COUT), .HIN(L6_HIN), .WIN(L6_WIN), .STRIDE(L6_STRIDE), .CLAMP(1'b1)
    ) u_conv6 (
        .clk(clk), .rst_n(rst_n), .start(conv6_start), .done(conv6_done),
        .in_addr(buf6_raddr), .in_data(buf6_rdata),
        .out_addr(buf7_waddr), .out_data(buf7_wdata), .out_we(buf7_we),
        .weight(L6_WEIGHT), .bias(L6_BIAS), .mult(L6_MULT), .shift(L6_SHIFT)
    );

    logic conv7_start, conv7_done;
    conv_engine #(
        .CIN(L7_CIN), .COUT(L7_COUT), .HIN(L7_HIN), .WIN(L7_WIN), .STRIDE(L7_STRIDE), .CLAMP(1'b1)
    ) u_conv7 (
        .clk(clk), .rst_n(rst_n), .start(conv7_start), .done(conv7_done),
        .in_addr(buf7_raddr), .in_data(buf7_rdata),
        .out_addr(buf8_waddr), .out_data(buf8_wdata), .out_we(buf8_we),
        .weight(L7_WEIGHT), .bias(L7_BIAS), .mult(L7_MULT), .shift(L7_SHIFT)
    );

    // ---- GAP + FC + argmax ----
    logic gap_start, gap_done;
    gap_fc_argmax #(
        .CF(FINAL_CF), .HF(FINAL_HF), .WF(FINAL_WF), .NCLS(NCLS)
    ) u_gap_fc (
        .clk(clk), .rst_n(rst_n), .start(gap_start), .done(gap_done),
        .feat_addr(buf8_raddr), .feat_data(buf8_rdata),
        .gap_mult(GAP_MULT), .gap_shift(GAP_SHIFT), .fc_weight(FC_WEIGHT), .fc_bias(FC_BIAS), .fc_mult(FC_MULT), .fc_shift(FC_SHIFT),
        .class_id(class_id), .class_scores(class_scores)
    );

    // ---- sequencing FSM: run layer 0, wait done, run layer 1, ... , then GAP+FC ----
    localparam int NSTAGE = 9; // N conv layers + 1 gap/fc stage
    typedef enum logic [1:0] {ST_IDLE, ST_RUN, ST_DONE} seq_state_t;
    seq_state_t seq_state;
    int stage;

    always_comb begin
        conv0_start = (seq_state == ST_RUN) && (stage == 0) && !conv0_done_d;
        conv1_start = (seq_state == ST_RUN) && (stage == 1) && !conv1_done_d;
        conv2_start = (seq_state == ST_RUN) && (stage == 2) && !conv2_done_d;
        conv3_start = (seq_state == ST_RUN) && (stage == 3) && !conv3_done_d;
        conv4_start = (seq_state == ST_RUN) && (stage == 4) && !conv4_done_d;
        conv5_start = (seq_state == ST_RUN) && (stage == 5) && !conv5_done_d;
        conv6_start = (seq_state == ST_RUN) && (stage == 6) && !conv6_done_d;
        conv7_start = (seq_state == ST_RUN) && (stage == 7) && !conv7_done_d;
        gap_start = (seq_state == ST_RUN) && (stage == 8) && !gap_done_d;
    end

    // rising-edge start pulses: only pulse start for one cycle when entering a stage
    logic conv0_done_d;
    logic conv1_done_d;
    logic conv2_done_d;
    logic conv3_done_d;
    logic conv4_done_d;
    logic conv5_done_d;
    logic conv6_done_d;
    logic conv7_done_d;
    logic gap_done_d;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            conv0_done_d <= 1'b0;
            conv1_done_d <= 1'b0;
            conv2_done_d <= 1'b0;
            conv3_done_d <= 1'b0;
            conv4_done_d <= 1'b0;
            conv5_done_d <= 1'b0;
            conv6_done_d <= 1'b0;
            conv7_done_d <= 1'b0;
            gap_done_d <= 1'b0;
            seq_state <= ST_IDLE;
            stage <= 0;
            done <= 1'b0;
        end else begin
            unique case (seq_state)
                ST_IDLE: begin
                    done <= 1'b0;
                    if (start) begin
                        stage <= 0;
                        conv0_done_d <= 1'b0;
                        conv1_done_d <= 1'b0;
                        conv2_done_d <= 1'b0;
                        conv3_done_d <= 1'b0;
                        conv4_done_d <= 1'b0;
                        conv5_done_d <= 1'b0;
                        conv6_done_d <= 1'b0;
                        conv7_done_d <= 1'b0;
                        gap_done_d <= 1'b0;
                        seq_state <= ST_RUN;
                    end
                end
                ST_RUN: begin
                    if (stage == 0 && conv0_done) conv0_done_d <= 1'b1;
                    if (stage == 1 && conv1_done) conv1_done_d <= 1'b1;
                    if (stage == 2 && conv2_done) conv2_done_d <= 1'b1;
                    if (stage == 3 && conv3_done) conv3_done_d <= 1'b1;
                    if (stage == 4 && conv4_done) conv4_done_d <= 1'b1;
                    if (stage == 5 && conv5_done) conv5_done_d <= 1'b1;
                    if (stage == 6 && conv6_done) conv6_done_d <= 1'b1;
                    if (stage == 7 && conv7_done) conv7_done_d <= 1'b1;
                    if (stage == 8 && gap_done) gap_done_d <= 1'b1;
                    if (stage < NSTAGE-1) begin
                        if (stage == 0 && conv0_done) stage <= stage + 1;
                        if (stage == 1 && conv1_done) stage <= stage + 1;
                        if (stage == 2 && conv2_done) stage <= stage + 1;
                        if (stage == 3 && conv3_done) stage <= stage + 1;
                        if (stage == 4 && conv4_done) stage <= stage + 1;
                        if (stage == 5 && conv5_done) stage <= stage + 1;
                        if (stage == 6 && conv6_done) stage <= stage + 1;
                        if (stage == 7 && conv7_done) stage <= stage + 1;
                    end else begin
                        if (gap_done) seq_state <= ST_DONE;
                    end
                end
                ST_DONE: begin
                    done <= 1'b1;
                    seq_state <= ST_IDLE;
                end
                default: seq_state <= ST_IDLE;
            endcase
        end
    end

endmodule
