# TCL File Generated by Component Editor 25.1
# Tue Sep 08 02:22:10 IST 2026
# DO NOT MODIFY


# 
# DE2_115_TV "DE2-115 TV Box" v1.0
# Terasic / User 2026.09.08.02:22:10
# DE2-115 TV Box top level wrapped for Platform Designer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DE2_115_TV
# 
set_module_property DESCRIPTION "DE2-115 TV Box top level wrapped for Platform Designer"
set_module_property NAME DE2_115_TV
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "DE2-115 Board"
set_module_property AUTHOR "Terasic / User"
set_module_property DISPLAY_NAME "DE2-115 TV Box"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH generate_synth_files ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DE2_115_TV
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true

add_fileset SIM_VERILOG SIM_VERILOG generate_sim_files ""
set_fileset_property SIM_VERILOG TOP_LEVEL DE2_115_TV
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk CLOCK_50 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input 2
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_readdata readdata Output 32
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 32
add_interface_port avs avs_waitrequest waitrequest Output 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_clocks
# 
add_interface conduit_clocks conduit end
set_interface_property conduit_clocks associatedClock ""
set_interface_property conduit_clocks associatedReset ""
set_interface_property conduit_clocks ENABLED true
set_interface_property conduit_clocks EXPORT_OF ""
set_interface_property conduit_clocks PORT_NAME_MAP ""
set_interface_property conduit_clocks CMSIS_SVD_VARIABLES ""
set_interface_property conduit_clocks SVD_ADDRESS_GROUP ""

add_interface_port conduit_clocks CLOCK2_50 clock2_50 Input 1
add_interface_port conduit_clocks CLOCK3_50 clock3_50 Input 1
add_interface_port conduit_clocks ENETCLK_25 enetclk_25 Input 1
add_interface_port conduit_clocks SMA_CLKIN sma_clkin Input 1
add_interface_port conduit_clocks SMA_CLKOUT sma_clkout Output 1


# 
# connection point conduit_user_io
# 
add_interface conduit_user_io conduit end
set_interface_property conduit_user_io associatedClock ""
set_interface_property conduit_user_io associatedReset ""
set_interface_property conduit_user_io ENABLED true
set_interface_property conduit_user_io EXPORT_OF ""
set_interface_property conduit_user_io PORT_NAME_MAP ""
set_interface_property conduit_user_io CMSIS_SVD_VARIABLES ""
set_interface_property conduit_user_io SVD_ADDRESS_GROUP ""

add_interface_port conduit_user_io LEDG ledg Output 9
add_interface_port conduit_user_io LEDR ledr Output 18
add_interface_port conduit_user_io KEY key Input 4
add_interface_port conduit_user_io SW sw Input 18


# 
# connection point conduit_seg7
# 
add_interface conduit_seg7 conduit end
set_interface_property conduit_seg7 associatedClock ""
set_interface_property conduit_seg7 associatedReset ""
set_interface_property conduit_seg7 ENABLED true
set_interface_property conduit_seg7 EXPORT_OF ""
set_interface_property conduit_seg7 PORT_NAME_MAP ""
set_interface_property conduit_seg7 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_seg7 SVD_ADDRESS_GROUP ""

add_interface_port conduit_seg7 HEX0 hex0 Output 7
add_interface_port conduit_seg7 HEX1 hex1 Output 7
add_interface_port conduit_seg7 HEX2 hex2 Output 7
add_interface_port conduit_seg7 HEX3 hex3 Output 7
add_interface_port conduit_seg7 HEX4 hex4 Output 7
add_interface_port conduit_seg7 HEX5 hex5 Output 7
add_interface_port conduit_seg7 HEX6 hex6 Output 7
add_interface_port conduit_seg7 HEX7 hex7 Output 7


# 
# connection point conduit_lcd
# 
add_interface conduit_lcd conduit end
set_interface_property conduit_lcd associatedClock ""
set_interface_property conduit_lcd associatedReset ""
set_interface_property conduit_lcd ENABLED true
set_interface_property conduit_lcd EXPORT_OF ""
set_interface_property conduit_lcd PORT_NAME_MAP ""
set_interface_property conduit_lcd CMSIS_SVD_VARIABLES ""
set_interface_property conduit_lcd SVD_ADDRESS_GROUP ""

add_interface_port conduit_lcd LCD_BLON lcd_blon Output 1
add_interface_port conduit_lcd LCD_DATA lcd_data Bidir 8
add_interface_port conduit_lcd LCD_EN lcd_en Output 1
add_interface_port conduit_lcd LCD_ON lcd_on Output 1
add_interface_port conduit_lcd LCD_RS lcd_rs Output 1
add_interface_port conduit_lcd LCD_RW lcd_rw Output 1


# 
# connection point conduit_uart
# 
add_interface conduit_uart conduit end
set_interface_property conduit_uart associatedClock ""
set_interface_property conduit_uart associatedReset ""
set_interface_property conduit_uart ENABLED true
set_interface_property conduit_uart EXPORT_OF ""
set_interface_property conduit_uart PORT_NAME_MAP ""
set_interface_property conduit_uart CMSIS_SVD_VARIABLES ""
set_interface_property conduit_uart SVD_ADDRESS_GROUP ""

add_interface_port conduit_uart UART_CTS uart_cts Output 1
add_interface_port conduit_uart UART_RTS uart_rts Input 1
add_interface_port conduit_uart UART_RXD uart_rxd Input 1
add_interface_port conduit_uart UART_TXD uart_txd Output 1


# 
# connection point conduit_ps2
# 
add_interface conduit_ps2 conduit end
set_interface_property conduit_ps2 associatedClock ""
set_interface_property conduit_ps2 associatedReset ""
set_interface_property conduit_ps2 ENABLED true
set_interface_property conduit_ps2 EXPORT_OF ""
set_interface_property conduit_ps2 PORT_NAME_MAP ""
set_interface_property conduit_ps2 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_ps2 SVD_ADDRESS_GROUP ""

add_interface_port conduit_ps2 PS2_CLK ps2_clk Bidir 1
add_interface_port conduit_ps2 PS2_DAT ps2_dat Bidir 1
add_interface_port conduit_ps2 PS2_CLK2 ps2_clk2 Bidir 1
add_interface_port conduit_ps2 PS2_DAT2 ps2_dat2 Bidir 1


# 
# connection point conduit_sdcard
# 
add_interface conduit_sdcard conduit end
set_interface_property conduit_sdcard associatedClock ""
set_interface_property conduit_sdcard associatedReset ""
set_interface_property conduit_sdcard ENABLED true
set_interface_property conduit_sdcard EXPORT_OF ""
set_interface_property conduit_sdcard PORT_NAME_MAP ""
set_interface_property conduit_sdcard CMSIS_SVD_VARIABLES ""
set_interface_property conduit_sdcard SVD_ADDRESS_GROUP ""

add_interface_port conduit_sdcard SD_CLK sd_clk Output 1
add_interface_port conduit_sdcard SD_CMD sd_cmd Bidir 1
add_interface_port conduit_sdcard SD_DAT sd_dat Bidir 4
add_interface_port conduit_sdcard SD_WP_N sd_wp_n Input 1


# 
# connection point conduit_vga
# 
add_interface conduit_vga conduit end
set_interface_property conduit_vga associatedClock ""
set_interface_property conduit_vga associatedReset ""
set_interface_property conduit_vga ENABLED true
set_interface_property conduit_vga EXPORT_OF ""
set_interface_property conduit_vga PORT_NAME_MAP ""
set_interface_property conduit_vga CMSIS_SVD_VARIABLES ""
set_interface_property conduit_vga SVD_ADDRESS_GROUP ""

add_interface_port conduit_vga VGA_B vga_b Output 8
add_interface_port conduit_vga VGA_BLANK_N vga_blank_n Output 1
add_interface_port conduit_vga VGA_CLK vga_clk Output 1
add_interface_port conduit_vga VGA_G vga_g Output 8
add_interface_port conduit_vga VGA_HS vga_hs Output 1
add_interface_port conduit_vga VGA_R vga_r Output 8
add_interface_port conduit_vga VGA_SYNC_N vga_sync_n Output 1
add_interface_port conduit_vga VGA_VS vga_vs Output 1


# 
# connection point conduit_audio
# 
add_interface conduit_audio conduit end
set_interface_property conduit_audio associatedClock ""
set_interface_property conduit_audio associatedReset ""
set_interface_property conduit_audio ENABLED true
set_interface_property conduit_audio EXPORT_OF ""
set_interface_property conduit_audio PORT_NAME_MAP ""
set_interface_property conduit_audio CMSIS_SVD_VARIABLES ""
set_interface_property conduit_audio SVD_ADDRESS_GROUP ""

add_interface_port conduit_audio AUD_ADCDAT aud_adcdat Input 1
add_interface_port conduit_audio AUD_ADCLRCK aud_adclrck Bidir 1
add_interface_port conduit_audio AUD_BCLK aud_bclk Bidir 1
add_interface_port conduit_audio AUD_DACDAT aud_dacdat Output 1
add_interface_port conduit_audio AUD_DACLRCK aud_daclrck Bidir 1
add_interface_port conduit_audio AUD_XCK aud_xck Output 1


# 
# connection point conduit_i2c
# 
add_interface conduit_i2c conduit end
set_interface_property conduit_i2c associatedClock ""
set_interface_property conduit_i2c associatedReset ""
set_interface_property conduit_i2c ENABLED true
set_interface_property conduit_i2c EXPORT_OF ""
set_interface_property conduit_i2c PORT_NAME_MAP ""
set_interface_property conduit_i2c CMSIS_SVD_VARIABLES ""
set_interface_property conduit_i2c SVD_ADDRESS_GROUP ""

add_interface_port conduit_i2c EEP_I2C_SCLK eep_i2c_sclk Output 1
add_interface_port conduit_i2c EEP_I2C_SDAT eep_i2c_sdat Bidir 1
add_interface_port conduit_i2c I2C_SCLK i2c_sclk Output 1
add_interface_port conduit_i2c I2C_SDAT i2c_sdat Bidir 1


# 
# connection point conduit_enet0
# 
add_interface conduit_enet0 conduit end
set_interface_property conduit_enet0 associatedClock ""
set_interface_property conduit_enet0 associatedReset ""
set_interface_property conduit_enet0 ENABLED true
set_interface_property conduit_enet0 EXPORT_OF ""
set_interface_property conduit_enet0 PORT_NAME_MAP ""
set_interface_property conduit_enet0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_enet0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_enet0 ENET0_GTX_CLK enet0_gtx_clk Output 1
add_interface_port conduit_enet0 ENET0_INT_N enet0_int_n Input 1
add_interface_port conduit_enet0 ENET0_MDC enet0_mdc Output 1
add_interface_port conduit_enet0 ENET0_MDIO enet0_mdio Bidir 1
add_interface_port conduit_enet0 ENET0_RST_N enet0_rst_n Output 1
add_interface_port conduit_enet0 ENET0_RX_CLK enet0_rx_clk Input 1
add_interface_port conduit_enet0 ENET0_RX_COL enet0_rx_col Input 1
add_interface_port conduit_enet0 ENET0_RX_CRS enet0_rx_crs Input 1
add_interface_port conduit_enet0 ENET0_RX_DATA enet0_rx_data Input 4
add_interface_port conduit_enet0 ENET0_RX_DV enet0_rx_dv Input 1
add_interface_port conduit_enet0 ENET0_RX_ER enet0_rx_er Input 1
add_interface_port conduit_enet0 ENET0_TX_CLK enet0_tx_clk Input 1
add_interface_port conduit_enet0 ENET0_TX_DATA enet0_tx_data Output 4
add_interface_port conduit_enet0 ENET0_TX_EN enet0_tx_en Output 1
add_interface_port conduit_enet0 ENET0_TX_ER enet0_tx_er Output 1
add_interface_port conduit_enet0 ENET0_LINK100 enet0_link100 Input 1


# 
# connection point conduit_enet1
# 
add_interface conduit_enet1 conduit end
set_interface_property conduit_enet1 associatedClock ""
set_interface_property conduit_enet1 associatedReset ""
set_interface_property conduit_enet1 ENABLED true
set_interface_property conduit_enet1 EXPORT_OF ""
set_interface_property conduit_enet1 PORT_NAME_MAP ""
set_interface_property conduit_enet1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_enet1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_enet1 ENET1_GTX_CLK enet1_gtx_clk Output 1
add_interface_port conduit_enet1 ENET1_INT_N enet1_int_n Input 1
add_interface_port conduit_enet1 ENET1_MDC enet1_mdc Output 1
add_interface_port conduit_enet1 ENET1_MDIO enet1_mdio Bidir 1
add_interface_port conduit_enet1 ENET1_RST_N enet1_rst_n Output 1
add_interface_port conduit_enet1 ENET1_RX_CLK enet1_rx_clk Input 1
add_interface_port conduit_enet1 ENET1_RX_COL enet1_rx_col Input 1
add_interface_port conduit_enet1 ENET1_RX_CRS enet1_rx_crs Input 1
add_interface_port conduit_enet1 ENET1_RX_DATA enet1_rx_data Input 4
add_interface_port conduit_enet1 ENET1_RX_DV enet1_rx_dv Input 1
add_interface_port conduit_enet1 ENET1_RX_ER enet1_rx_er Input 1
add_interface_port conduit_enet1 ENET1_TX_CLK enet1_tx_clk Input 1
add_interface_port conduit_enet1 ENET1_TX_DATA enet1_tx_data Output 4
add_interface_port conduit_enet1 ENET1_TX_EN enet1_tx_en Output 1
add_interface_port conduit_enet1 ENET1_TX_ER enet1_tx_er Output 1
add_interface_port conduit_enet1 ENET1_LINK100 enet1_link100 Input 1


# 
# connection point conduit_tvdecoder
# 
add_interface conduit_tvdecoder conduit end
set_interface_property conduit_tvdecoder associatedClock ""
set_interface_property conduit_tvdecoder associatedReset ""
set_interface_property conduit_tvdecoder ENABLED true
set_interface_property conduit_tvdecoder EXPORT_OF ""
set_interface_property conduit_tvdecoder PORT_NAME_MAP ""
set_interface_property conduit_tvdecoder CMSIS_SVD_VARIABLES ""
set_interface_property conduit_tvdecoder SVD_ADDRESS_GROUP ""

add_interface_port conduit_tvdecoder TD_CLK27 td_clk27 Input 1
add_interface_port conduit_tvdecoder TD_DATA td_data Input 8
add_interface_port conduit_tvdecoder TD_HS td_hs Input 1
add_interface_port conduit_tvdecoder TD_RESET_N td_reset_n Output 1
add_interface_port conduit_tvdecoder TD_VS td_vs Input 1


# 
# connection point conduit_usb_otg
# 
add_interface conduit_usb_otg conduit end
set_interface_property conduit_usb_otg associatedClock ""
set_interface_property conduit_usb_otg associatedReset ""
set_interface_property conduit_usb_otg ENABLED true
set_interface_property conduit_usb_otg EXPORT_OF ""
set_interface_property conduit_usb_otg PORT_NAME_MAP ""
set_interface_property conduit_usb_otg CMSIS_SVD_VARIABLES ""
set_interface_property conduit_usb_otg SVD_ADDRESS_GROUP ""

add_interface_port conduit_usb_otg OTG_DATA otg_data Bidir 16
add_interface_port conduit_usb_otg OTG_ADDR otg_addr Output 2
add_interface_port conduit_usb_otg OTG_CS_N otg_cs_n Output 1
add_interface_port conduit_usb_otg OTG_WR_N otg_wr_n Output 1
add_interface_port conduit_usb_otg OTG_RD_N otg_rd_n Output 1
add_interface_port conduit_usb_otg OTG_INT otg_int Input 2
add_interface_port conduit_usb_otg OTG_RST_N otg_rst_n Output 1
add_interface_port conduit_usb_otg OTG_DREQ otg_dreq Input 2
add_interface_port conduit_usb_otg OTG_DACK_N otg_dack_n Output 2
add_interface_port conduit_usb_otg OTG_FSPEED otg_fspeed Bidir 1
add_interface_port conduit_usb_otg OTG_LSPEED otg_lspeed Bidir 1


# 
# connection point conduit_irda
# 
add_interface conduit_irda conduit end
set_interface_property conduit_irda associatedClock ""
set_interface_property conduit_irda associatedReset ""
set_interface_property conduit_irda ENABLED true
set_interface_property conduit_irda EXPORT_OF ""
set_interface_property conduit_irda PORT_NAME_MAP ""
set_interface_property conduit_irda CMSIS_SVD_VARIABLES ""
set_interface_property conduit_irda SVD_ADDRESS_GROUP ""

add_interface_port conduit_irda IRDA_RXD irda_rxd Input 1


# 
# connection point conduit_sdram
# 
add_interface conduit_sdram conduit end
set_interface_property conduit_sdram associatedClock ""
set_interface_property conduit_sdram associatedReset ""
set_interface_property conduit_sdram ENABLED true
set_interface_property conduit_sdram EXPORT_OF ""
set_interface_property conduit_sdram PORT_NAME_MAP ""
set_interface_property conduit_sdram CMSIS_SVD_VARIABLES ""
set_interface_property conduit_sdram SVD_ADDRESS_GROUP ""

add_interface_port conduit_sdram DRAM_ADDR dram_addr Output 13
add_interface_port conduit_sdram DRAM_BA dram_ba Output 2
add_interface_port conduit_sdram DRAM_CAS_N dram_cas_n Output 1
add_interface_port conduit_sdram DRAM_CKE dram_cke Output 1
add_interface_port conduit_sdram DRAM_CLK dram_clk Output 1
add_interface_port conduit_sdram DRAM_CS_N dram_cs_n Output 1
add_interface_port conduit_sdram DRAM_DQ dram_dq Bidir 32
add_interface_port conduit_sdram DRAM_DQM dram_dqm Output 4
add_interface_port conduit_sdram DRAM_RAS_N dram_ras_n Output 1
add_interface_port conduit_sdram DRAM_WE_N dram_we_n Output 1


# 
# connection point conduit_sram
# 
add_interface conduit_sram conduit end
set_interface_property conduit_sram associatedClock ""
set_interface_property conduit_sram associatedReset ""
set_interface_property conduit_sram ENABLED true
set_interface_property conduit_sram EXPORT_OF ""
set_interface_property conduit_sram PORT_NAME_MAP ""
set_interface_property conduit_sram CMSIS_SVD_VARIABLES ""
set_interface_property conduit_sram SVD_ADDRESS_GROUP ""

add_interface_port conduit_sram SRAM_ADDR sram_addr Output 20
add_interface_port conduit_sram SRAM_CE_N sram_ce_n Output 1
add_interface_port conduit_sram SRAM_DQ sram_dq Bidir 16
add_interface_port conduit_sram SRAM_LB_N sram_lb_n Output 1
add_interface_port conduit_sram SRAM_OE_N sram_oe_n Output 1
add_interface_port conduit_sram SRAM_UB_N sram_ub_n Output 1
add_interface_port conduit_sram SRAM_WE_N sram_we_n Output 1


# 
# connection point conduit_flash
# 
add_interface conduit_flash conduit end
set_interface_property conduit_flash associatedClock ""
set_interface_property conduit_flash associatedReset ""
set_interface_property conduit_flash ENABLED true
set_interface_property conduit_flash EXPORT_OF ""
set_interface_property conduit_flash PORT_NAME_MAP ""
set_interface_property conduit_flash CMSIS_SVD_VARIABLES ""
set_interface_property conduit_flash SVD_ADDRESS_GROUP ""

add_interface_port conduit_flash FL_ADDR fl_addr Output 23
add_interface_port conduit_flash FL_CE_N fl_ce_n Output 1
add_interface_port conduit_flash FL_DQ fl_dq Bidir 8
add_interface_port conduit_flash FL_OE_N fl_oe_n Output 1
add_interface_port conduit_flash FL_RST_N fl_rst_n Output 1
add_interface_port conduit_flash FL_RY fl_ry Input 1
add_interface_port conduit_flash FL_WE_N fl_we_n Output 1
add_interface_port conduit_flash FL_WP_N fl_wp_n Output 1


# 
# connection point conduit_gpio
# 
add_interface conduit_gpio conduit end
set_interface_property conduit_gpio associatedClock ""
set_interface_property conduit_gpio associatedReset ""
set_interface_property conduit_gpio ENABLED true
set_interface_property conduit_gpio EXPORT_OF ""
set_interface_property conduit_gpio PORT_NAME_MAP ""
set_interface_property conduit_gpio CMSIS_SVD_VARIABLES ""
set_interface_property conduit_gpio SVD_ADDRESS_GROUP ""

add_interface_port conduit_gpio GPIO gpio Bidir 36
add_interface_port conduit_gpio EX_IO ex_io Bidir 7

