//=============================================================================
// Avalon_Sdram_Port
//
// Avalon-MM slave giving a NiosV (or any Avalon master) single-word,
// random-access read/write into the shared SDRAM framebuffer, by driving
// the AV_* on-demand port added to Sdram_Control_4Port.
//
// avs_clk (Avalon/NiosV side) and sdram_clk (SDRAM controller's CLK,
// generated by Sdram_PLL from REF_CLK) may be different, asynchronous
// clocks. A toggle-flag handshake with 2-flop synchronizers crosses the
// request and the completion safely between domains. The address/write
// data bus is "quasi-static": the producer holds it constant from the
// moment the toggle flips until the transaction is acknowledged, and the
// consumer only samples it after synchronizing the toggle (>=2 cycles of
// margin), so no separate bus synchronizer is required for it. This is a
// standard, safe technique for infrequent, single-outstanding-request
// CDC handshakes.
//
// If avs_clk and sdram_clk happen to be the same clock in your design,
// this module still works correctly (the synchronizers just add two
// harmless extra cycles of latency).
//=============================================================================
module Avalon_Sdram_Port #(
    parameter ASIZE = 22,   // must match `ASIZE in Sdram_Params.h
    parameter DSIZE = 32    // must match `DSIZE in Sdram_Params.h
)(
    //================= Avalon-MM slave (NiosV side) =================
    input                    avs_clk,
    input                    avs_reset_n,
    input   [ASIZE-1:0]      avs_address,
    input                    avs_read,
    input                    avs_write,
    input   [DSIZE-1:0]      avs_writedata,
    output reg [DSIZE-1:0]   avs_readdata,
    output                   avs_waitrequest,

    //================= SDRAM controller side =================
    input                    sdram_clk,
    input                    sdram_reset_n,
    output reg               AV_RD,
    output reg               AV_WR,
    output reg [ASIZE-1:0]   AV_ADDR,
    output reg [DSIZE-1:0]   AV_WDATA,
    input   [DSIZE-1:0]      AV_RDATA,
    input                    AV_DONE
);

//=========================================================================
// avs_clk domain: issue request, hold address/data static, wait for ack
//=========================================================================
reg              req_tog;       // flips each time a NEW request is launched
reg              req_is_write;
reg  [ASIZE-1:0] req_addr;
reg  [DSIZE-1:0] req_wdata;
reg              busy;

wire             new_req = (avs_read || avs_write) && !busy;

// waitrequest stays high for the whole transaction: on the accepting
// cycle (new_req) and every cycle busy is set, until ack_edge_avs clears it
assign avs_waitrequest = busy || (avs_read || avs_write);

always @(posedge avs_clk or negedge avs_reset_n) begin
    if(!avs_reset_n) begin
        req_tog      <= 1'b0;
        busy         <= 1'b0;
        req_is_write <= 1'b0;
        req_addr     <= {ASIZE{1'b0}};
        req_wdata    <= {DSIZE{1'b0}};
        avs_readdata <= {DSIZE{1'b0}};
    end else begin
        if(new_req) begin
            req_is_write <= avs_write;
            req_addr     <= avs_address;
            req_wdata    <= avs_writedata;
            req_tog      <= ~req_tog;
            busy         <= 1'b1;
        end
        else if(busy && ack_edge_avs) begin
            avs_readdata <= sdram_rdata_sync;
            busy         <= 1'b0;
        end
    end
end

// 2-flop synchronizer: bring sdram-domain ack_tog into avs_clk domain
reg ack_tog_meta, ack_tog_sync, ack_tog_sync_d;
always @(posedge avs_clk or negedge avs_reset_n) begin
    if(!avs_reset_n) begin
        ack_tog_meta   <= 1'b0;
        ack_tog_sync   <= 1'b0;
        ack_tog_sync_d <= 1'b0;
    end else begin
        ack_tog_meta   <= ack_tog;          // from sdram domain (async)
        ack_tog_sync   <= ack_tog_meta;
        ack_tog_sync_d <= ack_tog_sync;
    end
end
wire ack_edge_avs = ack_tog_sync ^ ack_tog_sync_d;

// hold the read-data result stable for avs_clk to sample on ack_edge_avs
reg [DSIZE-1:0] sdram_rdata_sync;
always @(posedge avs_clk) sdram_rdata_sync <= rdata_hold;

//=========================================================================
// sdram_clk domain: synchronize the request toggle, run the transaction
//=========================================================================
reg req_tog_meta, req_tog_sync, req_tog_sync_d;
always @(posedge sdram_clk or negedge sdram_reset_n) begin
    if(!sdram_reset_n) begin
        req_tog_meta   <= 1'b0;
        req_tog_sync   <= 1'b0;
        req_tog_sync_d <= 1'b0;
    end else begin
        req_tog_meta   <= req_tog;          // from avs domain (async)
        req_tog_sync   <= req_tog_meta;
        req_tog_sync_d <= req_tog_sync;
    end
end
wire req_edge_sdram = req_tog_sync ^ req_tog_sync_d;

reg sd_state;                      // 0 = idle, 1 = waiting for AV_DONE
localparam SD_IDLE = 1'b0, SD_WAIT = 1'b1;
reg [DSIZE-1:0] rdata_hold;
reg ack_tog;

always @(posedge sdram_clk or negedge sdram_reset_n) begin
    if(!sdram_reset_n) begin
        AV_RD      <= 1'b0;
        AV_WR      <= 1'b0;
        AV_ADDR    <= {ASIZE{1'b0}};
        AV_WDATA   <= {DSIZE{1'b0}};
        rdata_hold <= {DSIZE{1'b0}};
        ack_tog    <= 1'b0;
        sd_state   <= SD_IDLE;
    end else begin
        AV_RD <= 1'b0;
        AV_WR <= 1'b0;
        case(sd_state)
        SD_IDLE: begin
            if(req_edge_sdram) begin
                AV_ADDR  <= req_addr;       // quasi-static, safe to sample
                AV_WDATA <= req_wdata;      // (see header comment)
                if(req_is_write) AV_WR <= 1'b1;
                else             AV_RD <= 1'b1;
                sd_state <= SD_WAIT;
            end
        end
        SD_WAIT: begin
            if(AV_DONE) begin
                rdata_hold <= AV_RDATA;
                ack_tog    <= ~ack_tog;
                sd_state   <= SD_IDLE;
            end
        end
        default: sd_state <= SD_IDLE;
        endcase
    end
end

endmodule
