#!/usr/bin/env python3
"""
gen_tcnn.py
===========
Parses tinycnn_qat_int4.onnx (4 conv layers + global-average-pool + FC head,
see docs/architecture.md) and emits everything the layer-pipelined RTL needs:

  gen/tcnn.json       - machine-readable layer list (shapes, strides, requant,
                         gap requant, head requant)
  gen/tcnn_pkg.sv     - SystemVerilog package: per-layer localparams + the
                         head/gap requant scalars
  gen/tcnn_paths.svh  - `define TCNN_GEN "<absolute path to gen/>"` so every
                         $readmemh in the RTL can use an absolute path
  gen/w_L{k}.hex      - packed per-pass weight ROM, one word per (co,pass),
                         lane j = tap*CIN_PAR+ci_local at bits [4j+3:4j], int4
  gen/b_L{k}.hex      - int32 bias per output channel, one line per co
  gen/m_L{k}.hex      - requant multiplier M0 per output channel (32-bit hex)
  gen/s_L{k}.hex      - requant shift per output channel (32-bit hex)
  gen/hw.hex          - head weights, 64 int4 values, order o*32+i
  gen/hb.hex          - head bias, 2 int32 values

<<<<<<< HEAD
This reuses onnx_to_rtl.py's find_conv_chain() (walks the
Conv/QuantizeLinear/DequantizeLinear sandwich) and quantize_multiplier() (the
TFLite-style M0/shift fixed-point requant scheme: real_multiplier == M0 *
2^-shift exactly, NO extra 2^-31 -- see that file's docstring) rather than
re-deriving them. (onnx_to_rtl.py was originally written for
fpga_cnn_pipeline/ and copied here, unmodified, when that project was
removed -- see docs/architecture.md.)
=======
This reuses fpga_cnn_pipeline/onnx_to_rtl.py's find_conv_chain() (walks the
Conv/QuantizeLinear/DequantizeLinear sandwich) and quantize_multiplier() (the
TFLite-style M0/shift fixed-point requant scheme: real_multiplier == M0 *
2^-shift exactly, NO extra 2^-31 -- see that file's docstring and
fpga_cnn_pipeline/docs/review_findings.md B1) rather than re-deriving them.
>>>>>>> 99b8fe1 (get a working cnn in fpga)

Usage:
    pip install onnx numpy
    python3 gen_tcnn.py tinycnn_qat_int4.onnx --outdir gen --cin-par 3,16,8,16
"""
import argparse
import json
import os
import sys

import numpy as np
import onnx
from onnx import numpy_helper

<<<<<<< HEAD
sys.path.insert(0, os.path.dirname(__file__))
=======
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "fpga_cnn_pipeline"))
>>>>>>> 99b8fe1 (get a working cnn in fpga)
from onnx_to_rtl import find_conv_chain, quantize_multiplier, weight_bits  # noqa: E402


def get_inits(model):
    return {i.name: numpy_helper.to_array(i) for i in model.graph.initializer}


def find_gap_requant(model):
    """The graph's GlobalAveragePool step is really:
        ReduceMean over the 1 spatial position (a no-op after the last conv's
        4x4 -> ... wait, actually mean over [-1,-2] with keepdim, i.e. over
        the whole 4x4 spatial map) -> Reshape -> QuantizeLinear/DequantizeLinear.
    The RTL instead computes an INTEGER sum over the 16 (4x4) spatial
    positions per channel (not a float mean), then requantizes that sum
    directly to the 'view' uint8 code with a single M0/shift pair derived
    from the ratio of scales, folding in the /16 average as part of the
    fixed-point multiplier. This function derives that (M0, shift) pair.

    real_multiplier = relu_3_scale / (N_SPATIAL * view_scale)
    where N_SPATIAL is the number of spatial positions averaged (16 for a
    4x4 map), because sum/N_SPATIAL == mean, and requant maps the sum's
    integer scale (relu_3_scale per element) to view_scale after that /N.
    """
    inits = get_inits(model)
    relu_3_scale = float(inits["relu_3_scale"])
    view_scale = float(inits["view_scale"])
    view_zp = int(inits["view_zero_point"])
    return relu_3_scale, view_scale, view_zp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("onnx_path")
    ap.add_argument("--outdir", default="gen")
    ap.add_argument("--cin-par", default="3,16,8,16",
                     help="comma-separated CIN_PAR per conv layer (default matches "
                          "the 1024-cycle/tile schedule in docs/architecture.md)")
    ap.add_argument("--n-spatial", type=int, default=16,
                     help="number of spatial positions averaged by the GAP "
                          "(4x4 feature map -> 16); must match the last conv "
                          "layer's OH*OW")
    args = ap.parse_args()

    cin_par = [int(x) for x in args.cin_par.split(",")]

    model = onnx.load(args.onnx_path)
    convs, head = find_conv_chain(model)
    assert len(convs) == 4, f"expected 4 conv layers, got {len(convs)}"
    assert len(cin_par) == 4, f"--cin-par must have 4 values, got {cin_par}"

    wbits = weight_bits(convs[0]["w_q"])
    assert wbits == 4, f"expected int4 weights, got {wbits}-bit"
    wmask = (1 << wbits) - 1

    outdir = args.outdir
    os.makedirs(outdir, exist_ok=True)

    layers_json = []
    sv_lines = []
    sv_lines.append("// AUTO-GENERATED by gen_tcnn.py -- do not edit by hand")
    sv_lines.append("package tcnn_pkg;")
    sv_lines.append("  localparam int NUM_LAYERS = 4;")
    sv_lines.append("")

    ih_running = 16  # first conv's input spatial size (16x16 tile)
    for li, c in enumerate(convs):
        OC, IC, KH, KW = c["w_q"].shape
        assert (KH, KW) == (3, 3), f"layer {li}: expected 3x3 kernel, got {KH}x{KW}"
        assert c["stride"][0] == c["stride"][1]
        stride = c["stride"][0]
        pad = c["pads"][0]
        par = cin_par[li]
        assert IC % par == 0, f"layer {li}: CIN={IC} not divisible by CIN_PAR={par}"
        npass = IC // par

        oh = (ih_running + 2 * pad - 3) // stride + 1
        ow = oh  # square tiles throughout

        # all weight/bias zero-points must be 0 (verified against this model
        # in the planning session; assert here so a different model fails
        # loudly instead of silently producing wrong RTL)
        assert int(c["w_zp"].max()) == 0 and int(c["w_zp"].min()) == 0, \
            f"layer {li}: nonzero weight zero-point, not supported"
        assert c["in_zp"] == 0 and c["out_zp"] == 0, \
            f"layer {li}: nonzero activation zero-point, not supported"

        # per-channel requant
        mults, shifts = [], []
        for oc in range(OC):
            real_mult = (c["in_scale"] * float(c["w_scale"][oc])) / c["out_scale"]
            m0, rs = quantize_multiplier(real_mult)
            mults.append(m0)
            shifts.append(rs)

        # --- packed weight ROM: address = co*npass + p, lane j = tap*par + ci_local
        # bits [4j+3:4j] = w[co][p*par+ci_local][ky][kx], two's complement int4
        rom_words = []
        for oc in range(OC):
            for p in range(npass):
                lane_val = 0
                for tap in range(9):
                    ky, kx = divmod(tap, 3)
                    for ci_local in range(par):
                        ci = p * par + ci_local
                        wv = int(c["w_q"][oc, ci, ky, kx]) & wmask
                        j = tap * par + ci_local
                        lane_val |= wv << (4 * j)
                rom_words.append(lane_val)
        nhex_word = (par * 9 * 4 + 3) // 4
        with open(os.path.join(outdir, f"w_L{li}.hex"), "w") as f:
            for w in rom_words:
                f.write(f"{w:0{nhex_word}x}\n")

        with open(os.path.join(outdir, f"b_L{li}.hex"), "w") as f:
            for v in c["bias_q"]:
                f.write(f"{int(v) & 0xFFFFFFFF:08x}\n")
        with open(os.path.join(outdir, f"m_L{li}.hex"), "w") as f:
            for m in mults:
                f.write(f"{int(m) & 0xFFFFFFFF:08x}\n")
        with open(os.path.join(outdir, f"s_L{li}.hex"), "w") as f:
            for s in shifts:
                f.write(f"{int(s) & 0xFFFFFFFF:08x}\n")

        cycles_per_tile = oh * ow * OC * npass
        layers_json.append(dict(
            idx=li, name=c["name"], in_ch=IC, out_ch=OC, in_hw=ih_running,
            out_hw=oh, stride=stride, pad=pad, cin_par=par, npass=npass,
            in_zp=c["in_zp"], out_zp=c["out_zp"],
            mults=mults, shifts=shifts, cycles_per_tile=cycles_per_tile,
        ))

        sv_lines.append(f"  // layer {li}: {c['name']}  CIN={IC} COUT={OC} "
                          f"IN_HW={ih_running} OUT_HW={oh} stride={stride} "
                          f"CIN_PAR={par} NPASS={npass} cycles/tile={cycles_per_tile}")
        sv_lines.append(f"  localparam int L{li}_CIN    = {IC};")
        sv_lines.append(f"  localparam int L{li}_COUT   = {OC};")
        sv_lines.append(f"  localparam int L{li}_IN_HW  = {ih_running};")
        sv_lines.append(f"  localparam int L{li}_OUT_HW = {oh};")
        sv_lines.append(f"  localparam int L{li}_STRIDE = {stride};")
        sv_lines.append(f"  localparam int L{li}_PAD    = {pad};")
        sv_lines.append(f"  localparam int L{li}_CIN_PAR= {par};")
        sv_lines.append(f"  localparam int L{li}_NPASS  = {npass};")
        sv_lines.append(f"  localparam int L{li}_ROM_DEPTH = {OC * npass};")
        sv_lines.append(f"  localparam int L{li}_ROM_WBITS = {par * 9 * 4};")
        sv_lines.append("")

        ih_running = oh

    assert ih_running * ih_running == args.n_spatial, \
        f"final conv spatial size {ih_running}x{ih_running} != --n-spatial {args.n_spatial}"

    # ---- head GEMM (32 -> 2) ----
    OC2, IC2 = head["w_q"].shape
    # head weight zero-point isn't threaded through find_conv_chain()'s return
    # dict (only w_q/w_scale/bias_q/in_scale/in_zp/out_scale/out_zp); verified
    # directly against the ONNX initializers in the planning session that
    # head.weight_zero_point is all-zero for this model, so only in_zp is
    # checked here (that one *is* available).
    assert head["in_zp"] == 0

    with open(os.path.join(outdir, "hw.hex"), "w") as f:
        for oc in range(OC2):
            for ic in range(IC2):
                iv = int(head["w_q"][oc, ic]) & wmask
                f.write(f"{iv:01x}\n")
    with open(os.path.join(outdir, "hb.hex"), "w") as f:
        for v in head["bias_q"]:
            f.write(f"{int(v) & 0xFFFFFFFF:08x}\n")

    head_mults, head_shifts = [], []
    for oc in range(OC2):
        real_mult = (head["in_scale"] * float(head["w_scale"][oc])) / head["out_scale"]
        m0, rs = quantize_multiplier(real_mult)
        head_mults.append(m0)
        head_shifts.append(rs)

    # ---- GAP requant: sum over N_SPATIAL positions -> requant to view_scale ----
    relu_3_scale, view_scale, view_zp = find_gap_requant(model)
    gap_real_mult = relu_3_scale / (args.n_spatial * view_scale)
    gap_m0, gap_sh = quantize_multiplier(gap_real_mult)

    sv_lines.append(f"  // head GEMM: CIN={IC2} COUT={OC2}")
    sv_lines.append(f"  localparam int HEAD_CIN  = {IC2};")
    sv_lines.append(f"  localparam int HEAD_COUT = {OC2};")
    sv_lines.append(f"  localparam int HEAD_IN_ZP  = {head['in_zp']};")
    sv_lines.append(f"  localparam int HEAD_OUT_ZP = {head['out_zp']};")
    sv_lines.append(f"  localparam int HEAD_MULT [0:{OC2-1}] = '{{{', '.join(map(str,head_mults))}}};")
    sv_lines.append(f"  localparam int HEAD_SHIFT[0:{OC2-1}] = '{{{', '.join(map(str,head_shifts))}}};")
    sv_lines.append("")
    sv_lines.append(f"  // global-average-pool requant: sum over N_SPATIAL={args.n_spatial} "
                      f"positions, then requant sum -> view_scale (folds /N_SPATIAL into M0/shift)")
    sv_lines.append(f"  localparam int GAP_N_SPATIAL = {args.n_spatial};")
    sv_lines.append(f"  localparam int GAP_MULT  = {gap_m0};")
    sv_lines.append(f"  localparam int GAP_SHIFT = {gap_sh};")
    sv_lines.append(f"  localparam int GAP_OUT_ZP = {view_zp};")
    sv_lines.append(f"  localparam int LOGIT_ZP = {head['out_zp']};")
    sv_lines.append("endpackage")

    with open(os.path.join(outdir, "tcnn_pkg.sv"), "w") as f:
        f.write("\n".join(sv_lines) + "\n")

    gen_abspath = os.path.abspath(outdir)
    with open(os.path.join(outdir, "tcnn_paths.svh"), "w") as f:
        f.write("// AUTO-GENERATED by gen_tcnn.py -- do not edit by hand\n")
        f.write(f'`define TCNN_GEN "{gen_abspath}/"\n')
        # Full-literal path macros for every ROM file, in addition to
        # TCNN_GEN above. Quartus Prime's synthesis elaborator rejects
        # string concatenation ({GEN_DIR,"w_L0.hex"}) as a module parameter
        # binding ("SystemVerilog error: ... has an aggregate value"), even
        # though Verilator accepts it -- found via Phase 2 (tiny_cnn Gate
        # P2). A plain string-literal macro like this one sidesteps that:
        # the preprocessor substitutes it before parameter elaboration ever
        # sees a concatenation. tcnn_core.sv uses these macros directly
        # instead of `{GEN_DIR, "..."}` at each conv_layer/gap_head
        # instantiation.
        for k in range(4):
            f.write(f'`define TCNN_W_L{k} "{gen_abspath}/w_L{k}.hex"\n')
            f.write(f'`define TCNN_B_L{k} "{gen_abspath}/b_L{k}.hex"\n')
            f.write(f'`define TCNN_M_L{k} "{gen_abspath}/m_L{k}.hex"\n')
            f.write(f'`define TCNN_S_L{k} "{gen_abspath}/s_L{k}.hex"\n')
        f.write(f'`define TCNN_HW "{gen_abspath}/hw.hex"\n')
        f.write(f'`define TCNN_HB "{gen_abspath}/hb.hex"\n')

    with open(os.path.join(outdir, "tcnn.json"), "w") as f:
        json.dump(dict(
            layers=layers_json, wbits=wbits,
            head=dict(in_ch=IC2, out_ch=OC2, mults=head_mults, shifts=head_shifts,
                      in_zp=head["in_zp"], out_zp=head["out_zp"]),
            gap=dict(n_spatial=args.n_spatial, mult=gap_m0, shift=gap_sh,
                     out_zp=view_zp, in_scale=relu_3_scale, out_scale=view_scale),
        ), f, indent=2)

    print(f"weight bit-width: {wbits}-bit")
    print(f"CIN_PAR per layer: {cin_par}")
    for l in layers_json:
        print(f"  layer {l['idx']}: CIN={l['in_ch']} COUT={l['out_ch']} "
              f"{l['in_hw']}x{l['in_hw']}->{l['out_hw']}x{l['out_hw']} "
              f"stride={l['stride']} CIN_PAR={l['cin_par']} NPASS={l['npass']} "
              f"cycles/tile={l['cycles_per_tile']}")
    print(f"GAP: N_SPATIAL={args.n_spatial} M0={gap_m0} shift={gap_sh}")
    print(f"Wrote gen files to {outdir}/")


if __name__ == "__main__":
    main()
