// AUTO-GENERATED by gen_tcnn.py -- do not edit by hand
package tcnn_pkg;
  localparam int NUM_LAYERS = 4;

  // layer 0: node_Conv_68  CIN=3 COUT=16 IN_HW=16 OUT_HW=8 stride=2 CIN_PAR=3 NPASS=1 cycles/tile=1024
  localparam int L0_CIN    = 3;
  localparam int L0_COUT   = 16;
  localparam int L0_IN_HW  = 16;
  localparam int L0_OUT_HW = 8;
  localparam int L0_STRIDE = 2;
  localparam int L0_PAD    = 1;
  localparam int L0_CIN_PAR= 3;
  localparam int L0_NPASS  = 1;
  localparam int L0_ROM_DEPTH = 16;
  localparam int L0_ROM_WBITS = 108;

  // layer 1: node_Conv_70  CIN=16 COUT=16 IN_HW=8 OUT_HW=8 stride=1 CIN_PAR=16 NPASS=1 cycles/tile=1024
  localparam int L1_CIN    = 16;
  localparam int L1_COUT   = 16;
  localparam int L1_IN_HW  = 8;
  localparam int L1_OUT_HW = 8;
  localparam int L1_STRIDE = 1;
  localparam int L1_PAD    = 1;
  localparam int L1_CIN_PAR= 16;
  localparam int L1_NPASS  = 1;
  localparam int L1_ROM_DEPTH = 16;
  localparam int L1_ROM_WBITS = 576;

  // layer 2: node_Conv_72  CIN=16 COUT=32 IN_HW=8 OUT_HW=4 stride=2 CIN_PAR=8 NPASS=2 cycles/tile=1024
  localparam int L2_CIN    = 16;
  localparam int L2_COUT   = 32;
  localparam int L2_IN_HW  = 8;
  localparam int L2_OUT_HW = 4;
  localparam int L2_STRIDE = 2;
  localparam int L2_PAD    = 1;
  localparam int L2_CIN_PAR= 8;
  localparam int L2_NPASS  = 2;
  localparam int L2_ROM_DEPTH = 64;
  localparam int L2_ROM_WBITS = 288;

  // layer 3: node_Conv_74  CIN=32 COUT=32 IN_HW=4 OUT_HW=4 stride=1 CIN_PAR=16 NPASS=2 cycles/tile=1024
  localparam int L3_CIN    = 32;
  localparam int L3_COUT   = 32;
  localparam int L3_IN_HW  = 4;
  localparam int L3_OUT_HW = 4;
  localparam int L3_STRIDE = 1;
  localparam int L3_PAD    = 1;
  localparam int L3_CIN_PAR= 16;
  localparam int L3_NPASS  = 2;
  localparam int L3_ROM_DEPTH = 64;
  localparam int L3_ROM_WBITS = 576;

  // head GEMM: CIN=32 COUT=2
  localparam int HEAD_CIN  = 32;
  localparam int HEAD_COUT = 2;
  localparam int HEAD_IN_ZP  = 0;
  localparam int HEAD_OUT_ZP = 123;
  localparam int HEAD_MULT [0:1] = '{1151030682, 1209549403};
  localparam int HEAD_SHIFT[0:1] = '{33, 33};

  // global-average-pool requant: sum over N_SPATIAL=16 positions, then requant sum -> view_scale (folds /N_SPATIAL into M0/shift)
  localparam int GAP_N_SPATIAL = 16;
  localparam int GAP_MULT  = 1140694085;
  localparam int GAP_SHIFT = 33;
  localparam int GAP_OUT_ZP = 0;
  localparam int LOGIT_ZP = 123;
endpackage
